# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hack The Paygap
email: benjamin.willman@pif.gov
description: > # this means to ignore newlines until "baseurl:"
  Mobilizing companies, developers and women to take actions to reduce the gender pay gap.
baseurl: "" # the subpath of your site, e.g. /blog
email: opportunity-data@listserv.gsa.gov
url: https://paygap.pif.gov # the base hostname & protocol for your site
repo_url: https://github.com/presidential-innovation-fellows/hack-the-paygap

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

# Play nice with US Design Standards without needing to modify them (drop-in).
sass:
  sass_dir: scss

exclude:
  - Gemfile
  - Gemfile.lock
  - README.me
  - LICENSE.md
  - about.yml
  - system-security-plan.yml
  - CONTRIBUTING.md
  - node_modules
